# TESTE K-MEANS

Verificar a performance do classificador não supervisionado K-means no agrupamento dos dados. Os dados serão representados como bag-of-words (unigram, bigram e léxico de adjetivos)

## Obtenção dos dados

In [1]:
from database_utils import DatabaseConnector, build_dataframe

db_connector = DatabaseConnector('localhost', 'root', '12345', 'CORPUS_VIES')
retrieved_data = build_dataframe(db_connector.getDataTextAndLabel())

N_paragraphs = retrieved_data.shape[0]

SELECT PARAGRAPH, POLARITY FROM PARAGRAPHS WHERE POLARITY IS NOT NULL AND trim(POLARITY) <> ""
1042  Paragraphs encountered


## Importando as bibliotecas necessárias

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from machine_learning_utils import MLWrapper
from machine_learning_utils import Stemmer
from sklearn.pipeline import Pipeline
from nltk.corpus import stopwords

from sklearn.cluster import KMeans

import numpy as np

## Testando com unigramas

In [6]:
input_data = retrieved_data[(retrieved_data['labels'] == "PO") | (retrieved_data['labels'] == "NG")]
input_data['labels'].replace(to_replace = "NG", value = 0, inplace = True)
input_data['labels'].replace(to_replace = "PO", value = 1, inplace = True)


/home/caiomagno/anaconda3/lib/python3.5/site-packages/pandas/core/generic.py:3443: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)


In [9]:
print("Usando somente os unigramas")
pipeline = Pipeline([
        ('vectorizer', CountVectorizer()),
        ('classifier', KMeans(n_clusters=2))
    ])

ml = MLWrapper(pipeline)
ml.train(input_data, 2)

print("Usando somente os unigramas e removendo as stopwords")
pipeline = Pipeline([
        ('vectorizer', CountVectorizer(stop_words=stopwords.words('portuguese'))),
        ('classifier', KMeans(n_clusters=2))
    ])

ml = MLWrapper(pipeline)
ml.train(input_data, 2)

print("Usando somente o TFiDF")
pipeline = Pipeline([
        ('vectorizer', TfidfVectorizer()),
        ('classifier', KMeans(n_clusters=2))
    ])

ml = MLWrapper(pipeline)
ml.train(input_data, 2)


Usando somente os unigramas


/home/caiomagno/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64.
  warnings.warn(msg, DataConversionWarning)
/home/caiomagno/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64.
  warnings.warn(msg, DataConversionWarning)
/home/caiomagno/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64.
  warnings.warn(msg, DataConversionWarning)
/home/caiomagno/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64.
  warnings.warn(msg, DataConversionWarning)
/home/caiomagno/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64.
  wa

Total news classified: 701
Score: 0.40678637734
Accuracy: 0.516651930445
Confusion matrix:
[[200 191]
 [148 162]]
Usando somente os unigramas e removendo as stopwords


/home/caiomagno/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64.
  warnings.warn(msg, DataConversionWarning)
/home/caiomagno/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64.
  warnings.warn(msg, DataConversionWarning)
/home/caiomagno/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64.
  warnings.warn(msg, DataConversionWarning)
/home/caiomagno/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64.
  warnings.warn(msg, DataConversionWarning)
/home/caiomagno/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64.
  wa

Total news classified: 701
Score: 0.456017950035
Accuracy: 0.49377394636
Confusion matrix:
[[133 258]
 [ 97 213]]
Usando somente o TFiDF
Total news classified: 701
Score: 0.484496162689
Accuracy: 0.515129187543
Confusion matrix:
[[148 243]
 [ 97 213]]


In [22]:
# Separando os dados em treino e teste


labels                                              texts
25     PO  Marina ainda comentou na TV o resultado do Ide...
26     PO  Segundo aliados  as acusações de que Marina nã...